window.__justep.__ResourceEngine.loadCss([{url: '/v_4677_nol_zh_CNs_d_/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/justep/panel/css/panel,$model/system/components/justep/common/css/scrollable,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar'},{url: '/v_4677_nol_zh_CNs_d_/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/v_4677_nol_zh_CNs_d_/system/components/comp.min.js','/v_4677_nol_zh_CNs_d_/system/common.min.js','/v_4677_nol_zh_CNs_d_/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/panel/panel');
require('$model/UI2/system/components/justep/panel/child');
require('$model/UI2/system/components/justep/scrollView/scrollView');
require('$model/UI2/system/components/justep/button/buttonGroup');
require('$model/UI2/system/components/justep/contents/content');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/justep/titleBar/titleBar');
require('$model/UI2/system/components/justep/contents/contents');
require('$model/UI2/system/components/justep/button/button');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/LH_Team/channel/dynamic'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='';
	this.__cid='cmI7fiq';
	this._flag_='48ad1d5d0106d5c2e27f753cfa2bac5d';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"id":{"define":"id","label":"id","name":"id","relation":"id","type":"String"},"imgUrl":{"define":"imgUrl","label":"imgUrl","name":"imgUrl","relation":"imgUrl","type":"String"},"intro":{"define":"intro","label":"intro","name":"intro","relation":"intro","type":"String"},"title":{"define":"title","label":"title","name":"title","relation":"title","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","initData":"[{\"id\":\"1\",\"imgUrl\":\"./img/pic1.jpg\",\"title\":\"盖世大屏安卓智能 三星i9500降至2500\",\"intro\":\"提示：购买水货手机没有质量保障，请谨慎选择！　　[上海行情] 三星Galaxy S4(参数 报价 论...\"},{\"id\":\"2\",\"imgUrl\":\"./img/pic2.jpg\",\"title\":\"英雄气短：Palm手机重登ebay 只要10.5美元\",\"intro\":\"国人喜欢上淘宝淘低价宝贝，而外国人则选择ebay，ebay上经常会冒出许多“断码大甩卖”的好东...\"},{\"id\":\"3\",\"imgUrl\":\"./img/pic3.jpg\",\"title\":\"iPhone 5s或将过时 指纹触控屏今年夏天问世\",\"intro\":\"指纹扫描技术是今年MWC大会上的一个主流趋势，在今年，智能设备上的指纹传感器会发生翻天覆...\"},{\"id\":\"4\",\"imgUrl\":\"./img/pic4.jpg\",\"title\":\"四核配置拍照手机 诺基亚1520报价3610\",\"intro\":\"文/李则毅　　[北京行情] 2014年3月12日，诺基亚Lumia 1520(参数 报价 论坛 软件)(行货)今日...\"},{\"id\":\"5\",\"imgUrl\":\"./img/pic9.jpg\",\"title\":\"用数据说话：iOS7.1为iPhone 4提速了多少？\",\"intro\":\"iOS7发布以来，一直为人诟病的就是系统的流畅度比此前有所下降，这一现象不止发生在老机...\"},{\"id\":\"6\",\"imgUrl\":\"./img/pic5.jpg\",\"title\":\"价格变化不大 土豪金iPhone 5s售4160\",\"intro\":\"文/庞超　　提示：购买水货手机没有质量保障，请谨慎选择！　　[上海行情] 2014年3月12日，...\"},{\"id\":\"7\",\"imgUrl\":\"./img/pic6.jpg\",\"title\":\"双卡千元高性价比 酷派5951部分评测\",\"intro\":\"作为第四代千元双待王，酷派5951的发布再次将国产千元双待机型升级，而这种升级也是由里到外...\"},{\"id\":\"8\",\"imgUrl\":\"./img/pic7.jpg\",\"title\":\"为小屏机正名 索尼Xperia Z1炫彩版评测\",\"intro\":\"曾经有一台顶级配置的手机摆在我面前，却没有珍惜，只因望见那比巴掌还大的屏幕，心中落下千...\"},{\"id\":\"9\",\"imgUrl\":\"./img/pic8.jpg\",\"title\":\"适合单手操作 4.5英寸内热门手机推荐\",\"intro\":\"文/Ediand　　这两年来手机界有一个主流趋势，就是屏幕尺寸越来越大。我们还记得当初iPhone ...\"},{\"id\":\"10\",\"imgUrl\":\"./img/pic9.jpg\",\"title\":\"大屏iPhone 6曝光 将借鉴5c和nano设计\",\"intro\":\"爆料一向很准的日本博客Macotakara昨晚透露了苹果新iPhone产品线的更多细节：苹果今年设计了...\"}]","limit":20,"xid":"data"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"id":{"define":"id","label":"id","name":"id","relation":"id","type":"String"},"imgUrl":{"define":"imgUrl","label":"imgUrl","name":"imgUrl","relation":"imgUrl","type":"String"},"intro":{"define":"intro","label":"intro","name":"intro","relation":"intro","type":"String"},"title":{"define":"title","label":"title","name":"title","relation":"title","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","initData":"[{\"id\":\"1\",\"imgUrl\":\"./img/pic1.jpg\",\"title\":\"6寸强机对决 索尼T2 Ultra对比中兴Memo II\",\"intro\":\"不知从什么时候开始，智能手机市场对屏幕尺寸的质疑声消失了，随之一大波巨屏手机直接席卷了...\"},{\"id\":\"2\",\"imgUrl\":\"./img/pic2.jpg\",\"title\":\"供应链问题可能会导致索尼Xperia Z2推迟出货\",\"intro\":\"小道消息一向灵通的知名手机论坛Esato上的一名网友近日爆料，来自索尼的新旗舰Xperia Z2很可...\"},{\"id\":\"3\",\"imgUrl\":\"./img/pic3.jpg\",\"title\":\"带着手机去春游 拍照智能手机推荐\",\"intro\":\"转眼已经进入3月份，随着天气的逐渐转暖，是时候来一次说走就走的春游了。外出游玩，对手机...\"},{\"id\":\"4\",\"imgUrl\":\"./img/pic4.jpg\",\"title\":\"便宜实惠又好用 经典前旗舰手机推荐\",\"intro\":\"当年笔者在上大学期间，虽然喜欢玩手机，奈何钱包君不给力，尽量挑选水货，剩下不少钱，对于...\"},{\"id\":\"5\",\"imgUrl\":\"./img/pic5.jpg\",\"title\":\"或配光场相机 HTC M8双后镜头功能揭晓\",\"intro\":\"随着发布会的日益临近，HTC M8(All New HTC One)的曝光新闻逐渐增多，在这其中想必大家最为...\"},{\"id\":\"6\",\"imgUrl\":\"./img/pic6.png\",\"title\":\"三星申请柔性屏新专利 线路排布问题解决\",\"intro\":\"三星拥有柔性屏设计制造能力已经有一段时间了，不过现在我们还没有看到三星在该领域有太大的...\"},{\"id\":\"7\",\"imgUrl\":\"./img/pic7.jpg\",\"title\":\"iOS 8亮点多:改善地图新增交通服务\",\"intro\":\"苹果自从发布iOS 7系统以及iPhone 5s之后就消息不断，而果粉们最近关注的消息有苹果...\"},{\"id\":\"8\",\"imgUrl\":\"./img/pic8.jpg\",\"title\":\"奇葩视角 三星获21:9屏幕比例手机专利\",\"intro\":\"手机屏幕比例近两年从常见的4：3慢慢发展成为16：9，这一更加符合黄金分割的比例与大屏趋势...\"},{\"id\":\"9\",\"imgUrl\":\"./img/pic9.jpg\",\"title\":\"4GB内存/64位处理器？ 三星S5顶配版曝光\",\"intro\":\"新发布的三星新旗舰GALAXY;S5吸引不了你？为啥，是因为配置性能没有太大提升么？如果...\"},{\"id\":\"10\",\"imgUrl\":\"./img/pic1.jpg\",\"title\":\"13日行情:双四核手机联通双卡版报3480\",\"intro\":\"三星GALAXY S4绝对是当下手机市场中最炙手火热的智能机之一。这款手机采用了简约时尚...\"}]","limit":20,"xid":"data2"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"id":{"define":"id","label":"id","name":"id","relation":"id","type":"String"},"title":{"define":"title","label":"title","name":"title","relation":"title","type":"String"}},"directDelete":false,"events":{},"idColumn":"id","initData":"[{\"id\":\"1\",\"title\":\"高配何必多花钱 市售低价发烧手机盘点\"},{\"id\":\"2\",\"title\":\"Android仍是主流 热门学生智能手机一览\"},{\"id\":\"3\",\"title\":\"外观/配置并重 90后最佳之选的8大手机\"},{\"id\":\"4\",\"title\":\"天语发布电商品牌“nibiru”及首款手机H1\"},{\"id\":\"5\",\"title\":\"识别率高达98% 一加手机或将采用声纹解锁\"},{\"id\":\"6\",\"title\":\"跨界手机领头羊 港版三星Note3售3399\"},{\"id\":\"7\",\"title\":\"7英寸屏顶配手机 华为荣耀X1仅售1799\"},{\"id\":\"8\",\"title\":\"谷歌亲子最新系统 LG Nexus 5仅售2299\"},{\"id\":\"9\",\"title\":\"小米路由的新故事：做智能家居核心\"},{\"id\":\"10\",\"title\":\"3200mAh容量 双卡版Butterfly s售3180\"},{\"id\":\"11\",\"title\":\"个性拍照神器再降 三星S4 Zoom仅1580元\"},{\"id\":\"12\",\"title\":\"三防大屏实力派 索尼XL39h仅售2710元\"}]","limit":20,"xid":"data3"});
}}); 
return __result;});
